import type { NextPage } from 'next'
import Head from 'next/head'

import Footer from '../Components/Footer'
import Form from '../Components/Form'

import Header from '../Components/Header'
import { Container, Main } from '../styles/global'




const Home: NextPage = () => {
  return (
    <>

        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header/>

        <Main>
         <Container>
         <Form/>
         </Container>
      
        </Main>
        

      <Footer/>

    </>
  )
}

export default Home
